//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEmployee()
        {
            this.tblOrders = new HashSet<tblOrder>();
        }
    
        public int EmployeeID { get; set; }
        public string EmployeeFullName { get; set; }
        public System.DateTime Dob { get; set; }
        public int Age { get; set; }
        public long AdhaarNumber { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string Address { get; set; }
        public string District { get; set; }
        public int Pincode { get; set; }
        public string State { get; set; }
        public long ContactNumber { get; set; }
        public string EmailID { get; set; }
        public System.DateTime JoinDate { get; set; }
        public string OtherSubmittedProof { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrder> tblOrders { get; set; }
    }
}
